In [ ]:
import scipy.stats as st
import numpy as np

In [ ]:
#compute Expected number of observations under H0, and Observed in reality 
O = np.array([120,80,100])
E = np.array([120,90,90])

In [ ]:
#significace level of 5%
sl = 0.05

In [ ]:
#compute statistic for chi2
print(np.square(O-E)/E)
stat = (np.square(O-E)/E).sum()
stat

# here I'm just replicating the steps we did on the example

# And now we want to see if this value is very unlikly or not by computing the p_value 

[0.         1.11111111 1.11111111]


2.2222222222222223

In [ ]:
#check chi2-value for given significance (or confidence) level and the appriopriate number of degrees of freedom (number of categories -1)

st.chi2.sf(abs(stat),df=3-1)

# Here the degrees of freedom is a little bit diffrent from the t-distribution.
# The degrees of freedom are the number of categories (in this case number of items in the vending machine) minus 1.



0.3291929878079054

In [ ]:
#since our p value is relatively higher than (<5%), we do not reject our null

#should we reject?

0.3291929878079054 < 0.05

# so our vending machine would show enough evidence to say that it follows the UNILIVER distribution.
# so it is resonable to assume the Uniliver distribution (40%,30%,30%)

False

In [ ]:
#you can also do all of this in a line
## total number of bottles = 300

f_exp = np.array([0.4, 0.3,0.3]) * 300

st.chisquare([120,80,100], f_exp=[120,90,90])

Power_divergenceResult(statistic=2.2222222222222223, pvalue=0.3291929878079054)

In [ ]:
#do it yourself
#suppose we observed instead 180 cokes, 210 pepsis and 210 waters.
# Unilever sltill claim:
# 40% cokes, 30% pepsi, 30% water 

#Do we still not-reject at 1% significance?

In [ ]:
O = [180,210,210]
E = [0.4*600,0.3*600,0.3*600]

In [ ]:
#answer
print(st.chisquare([180,210,210], f_exp=[0.4*600,0.3*600,0.3*600]))

O = np.array([180,210,210])
E = np.array([240,180,180])


st.chi2.sf((np.square(O-E)/E).sum(),df=3-1)

Power_divergenceResult(statistic=25.0, pvalue=3.7266531720786718e-06)


3.7266531720786718e-06

In [ ]:
# this is a so rare deviation (p-value very very low, and smaller that the error we are acepting to commit) that I prefer 
# to reject my null hypotesis, that to belive that I hit the jackpot.

#SLIDES

In [ ]:
# Computing expected number of observations for distribution

In [ ]:
#for class
from scipy.stats import geom
p=0.3
geometric_dist = geom(p)

geometric_pmfs = np.array([geometric_dist.pmf(i) for i in range(1,11)]) #. up until 10
geometric_pmfs

array([0.3       , 0.21      , 0.147     , 0.1029    , 0.07203   ,
       0.050421  , 0.0352947 , 0.02470629, 0.0172944 , 0.01210608])

In [ ]:
#solving the problem
# I don't have the last value so I need to apend the last value wich is the cahnce of getting greater than ten
with_tail = np.append(geometric_pmfs,1-geometric_pmfs.sum()) #or np.append(geometric_pmfs, geometric_dist.sf(10)) #or np.append(geometric_pmfs, 1-geometric_dist.cdf(10))
print(with_tail)
E = with_tail*200
print(E)

[0.3        0.21       0.147      0.1029     0.07203    0.050421
 0.0352947  0.02470629 0.0172944  0.01210608 0.02824752]
[60.         42.         29.4        20.58       14.406      10.0842
  7.05894     4.941258    3.4588806   2.42121642  5.64950498]


In [ ]:
#let's comput at a 5% significance level

st.chisquare([55,40,38,28,10,6,9,1,2,4,7],f_exp=E)

# if we were doing by hand the number of dgrees of freedom would be 10 - 1

Power_divergenceResult(statistic=14.349488995700755, pvalue=0.15763881414387987)

In [ ]:
geometric_dist.pmf(0)
#we do not reject out hypothesis: this does seem to come from a geometric 0.3!

0.0

In [ ]:
## Now I want to show you that this is not an easy fit to do

#do it yourself
#does the distribution conform to a geometric 0.2?

In [ ]:
geometric_pmfs = np.array([geom(0.20).pmf(i) for i in range(1,11)])
E = np.append(geometric_pmfs,1-geometric_pmfs.sum())*200
st.chisquare([55,40,38,28,10,6,9,1,2,4,7],f_exp=E)

Power_divergenceResult(statistic=42.86458790302275, pvalue=5.258035233431057e-06)

In [ ]:
# In this example we were given what was the expected parameter for the geometric distribution.
# But we can gess this parameter by knowing that the mean is 1/p: https://en.wikipedia.org/wiki/Geometric_distribution 

# So if we belive this distibution came from a geometric distribution the mean should be a good approximation of 1/p.

# THe best way for me to do this, is to comput the mean of our observations.

In [ ]:
#mean = 1/p   <= > p = 1/mean

In [ ]:
p = 1/(np.array([55*1,40*2,38*3,28*4,10*5,6*6,9*7,1*8,2*9,4*10,7*11]).sum()/200) # I will comite a mistke because I don't have really good way to comput larger than 10 so I'm considering 11
p

0.30627871362940273

In [ ]:
#unknown parameter
#Estimated p = 0.306
geometric_pmfs = np.array([geom(0.306).pmf(i) for i in range(1,11)])
expected = np.append(geometric_pmfs,1-geometric_pmfs.sum())*200
st.chisquare([55,40,38,28,10,6,9,1,2,4,7],f_exp=expected)

NameError: ignored

In [ ]:
# So for all the distributions we have seen the parameter can be extrated from the mean and the mean can be extracted from the our observations

In [ ]:
# assuming a poisson now
# mean = lambda 

In [ ]:
(np.array([55*1,40*2,38*3,28*4,10*5,6*6,9*7,1*8,2*9,4*10,7*11]).sum()/200)

3.265

In [ ]:
from scipy.stats import poisson

In [ ]:
poisson_pmfs = np.array([poisson(3.265).pmf(i) for i in range(1,11)])
expected = np.append(poisson_pmfs,1-poisson_pmfs.sum())*200
st.chisquare([55,40,38,28,10,6,9,1,2,4,7],f_exp=expected)

Power_divergenceResult(statistic=101.81468891266596, pvalue=2.3600248735756413e-17)

In [ ]:
# Contingency tables and independence of effects
import scipy.stats as st

#we just need the observed values 

cars_table=[[256,74],
            [41,42],
            [66,34]]

st.chi2_contingency(np.array(cars_table))
#statistic, p-value, degrees of freedom, expected probs if H0 holds

(26.8113499370887,
 1.5065700686908928e-06,
 2,
 array([[233.50877193,  96.49122807],
        [ 58.73099415,  24.26900585],
        [ 70.76023392,  29.23976608]]))

In [ ]:
#seems like our car manufacturers are actually quite differentiated.
#good for them!

In [ ]:
#our conclusion is that the brands influence the preception 


### tuple from chi2_contingency:
### 1st element: statistic
### 2nd element: p_value
### 3rd element: degrees of freedom = (number of columns - 1)*(number of rows - 1)
### 4th element: the expected values if H0 stands true. If the car type is independent of the perception 




# we reject the null hypotesis 

## seems that our car manufacturers are actually quite diferenciated 
## seems that brands influence preception and perception influeces brands 