## Question 1
The following table indicates the number of 6-point scores in an American rugby match in the 1979 season.

![](table1.png)

Based on these results, we create a Poisson distribution with the sample mean parameter  = 2.435. Is there any reason to believe that at a .05 level the number of scores is a Poisson variable?

In [2]:
import scipy.stats as st
import numpy as np

In [38]:
# your answer here
#create a poisson dist
mu=2.435 # how do we calculate? 
poisson_dist = st.poisson(mu)

probabilities = np.array([poisson_dist.pmf(i) for i in range(7)]) 
probabilities = np.append(probabilities, 1-probabilities.sum())

#goodness of fit
O = np.array([35,99,104,110,62,25,10,3])
E = probabilities * O.sum()

print(O)
print(E)

test = st.chisquare(f_obs=O, f_exp=E)
print(test)


[ 35  99 104 110  62  25  10   3]
[ 39.24379068  95.5586303  116.34263239  94.43143662  57.48513704
  27.99526174  11.36141039   5.58170083]
Power_divergenceResult(statistic=6.491310681109821, pvalue=0.4836889068537269)


## BONUS/OPTIONAL - Question 2
Let's analyze a discrete distribution. To analyze the number of defective items in a factory in the city of Medellín, we took a random sample of n = 60 articles and observed the number of defectives in the following table:

![](table2.png)

A poissón distribution was proposed since it is defined for x = 0,1,2,3, .... using the following model:

![](image1.png)

For some extra insights check the following link: https://online.stat.psu.edu/stat504/node/63/ 

Does the distribution of defective items follow this distribution?

In [4]:
# your answer here
#create a poisson dist
mu= (0*32+15*1+7*13)/60
poisson_dist = st.poisson(mu)

probabilities = np.array([poisson_dist.pmf(i) for i in range(2)]) 
probabilities = np.append(probabilities, 1-probabilities.sum())

#goodness of fit
O = np.array([32, 15, 13])
E = probabilities * O.sum()

print(O)
print(E)

test = st.chisquare(f_obs=O, f_exp=E)
print(test)


[32 15 13]
[10.25410277 18.11558156 31.63031567]
Power_divergenceResult(statistic=57.62568965368859, pvalue=3.067188616933574e-13)


In [ ]:
# your code here

## Question 3
A quality control engineer takes a sample of 10 tires that come out of an assembly line, and would like to verify on the basis of the data that follows, if the number of tires with defects observed over 200 days, if it is true that 5% of all tires have defects (that is, if the sample comes from a binomial population with n = 10 and p = 0.05). 

![](table3.png)


In [7]:
# your answer here
# n - number of cases/experiments
# p - probability of success
binomial_dist = st.binom(n=10, p=0.05)

probabilities = np.array([binomial_dist.pmf(i) for i in range(2)]) 
probabilities = np.append(probabilities, 1-probabilities.sum())

#goodness of fit
O = np.array([138, 53, 9])
E = probabilities * O.sum()

print(O)
print(E)

test = st.chisquare(f_obs=O, f_exp=E)
print(test)


[138  53   9]
[119.74738785  63.02494097  17.22767118]
Power_divergenceResult(statistic=8.306179519542805, pvalue=0.015715783395950887)


## Question 4
A researcher gathers information about the patterns of Physical Activity of children in the fifth grade of primary school of a public school. He defines three categories of physical activity (Low, Medium, High). He also inquires about the regular consumption of sugary drinks at school, and defines two categories (Yes = consumed, No = not consumed). We would like to evaluate if there is an association between patterns of physical activity and the consumption of sugary drinks for the children of this school, at a level of 5% significance. The results are in the following table: 

![](table4.png)

In [8]:
#your answer here
obs_data=[[32,12], [14, 22], [6, 9]]

# significance level
alpha=0.05

st.chi2_contingency(np.array(obs_data))


(10.712198008709638,
 0.004719280137040844,
 2,
 array([[24.08421053, 19.91578947],
        [19.70526316, 16.29473684],
        [ 8.21052632,  6.78947368]]))

In [10]:
print("we reject H0, there is an association")

we reject H0, there is an association
