## Question 1
The following table indicates the number of 6-point scores in an American rugby match in the 1979 season.

![](table1.png)

Based on these results, we create a Poisson distribution with the sample mean parameter  = 2.435. Is there any reason to believe that at a .05 level the number of scores is a Poisson variable?

In [1]:
from scipy.stats import poisson
import numpy as np
import pandas as pd
import scipy.stats as st

In [8]:
# your answer here
p = 2.435
poisson_dist = poisson(p)
poisson_pmfs = np.array([poisson_dist.pmf(i) for i in range(0,7)])
poisson_pmfs

array([0.08759775, 0.21330051, 0.25969338, 0.21078446, 0.12831504,
       0.06248942, 0.02536029])

In [9]:
poisson_pmfs = np.append(poisson_pmfs, 1 - poisson_pmfs.sum())
poisson_pmfs

array([0.08759775, 0.21330051, 0.25969338, 0.21078446, 0.12831504,
       0.06248942, 0.02536029, 0.01245915])

In [10]:
E = poisson_pmfs*448
O = np.array([35,99,104,110,62,25,10,3])
st.chisquare(f_obs=O ,f_exp=E)

Power_divergenceResult(statistic=6.491310681109821, pvalue=0.483688906853727)

In [ ]:
# According to our pvalue we cannot reject the hipothesis that the sample follows a poisson distribution

## BONUS/OPTIONAL - Question 2
Let's analyze a discrete distribution. To analyze the number of defective items in a factory in the city of Medellín, we took a random sample of n = 60 articles and observed the number of defectives in the following table:

![](table2.png)

A poissón distribution was proposed since it is defined for x = 0,1,2,3, .... using the following model:

![](image1.png)

For some extra insights check the following link: https://online.stat.psu.edu/stat504/node/63/ 

Does the distribution of defective items follow this distribution?

In [ ]:
# your code here

## Question 3
A quality control engineer takes a sample of 10 tires that come out of an assembly line, and would like to verify on the basis of the data that follows, if the number of tires with defects observed over 200 days, if it is true that 5% of all tires have defects (that is, if the sample comes from a binomial population with n = 10 and p = 0.05). 

![](table3.png)


In [4]:
# your answer here
from scipy.stats import binom

n = 10
p = 0.05

binomial_dist = binom(n,p)
binomial_pmfs = np.array([binomial_dist.pmf(i) for i in range(0,2)])
binomial_pmfs

array([0.59873694, 0.3151247 ])

In [5]:
binomial_pmfs = np.append(binomial_pmfs, 1 - binomial_pmfs.sum())
binomial_pmfs

array([0.59873694, 0.3151247 , 0.08613836])

In [9]:
E = binomial_pmfs*200
O = np.array([138,53,9])
st.chisquare(f_obs=O ,f_exp=E)

Power_divergenceResult(statistic=8.306179519542757, pvalue=0.015715783395951262)

In [ ]:
# Pvalue is under 5% so we can reject the hypothises this follows a binomial distribution 

## Question 4
A researcher gathers information about the patterns of Physical Activity of children in the fifth grade of primary school of a public school. He defines three categories of physical activity (Low, Medium, High). He also inquires about the regular consumption of sugary drinks at school, and defines two categories (Yes = consumed, No = not consumed). We would like to evaluate if there is an association between patterns of physical activity and the consumption of sugary drinks for the children of this school, at a level of 5% significance. The results are in the following table: 

![](table4.png)

In [13]:
#your answer here
table1 = [[32,12],[14,22],[6,9]]
alpha = 0.05

st.chi2_contingency(table1)

# pvalue is under the alpha so we cannot say there is an association

Chi2ContingencyResult(statistic=10.712198008709638, pvalue=0.004719280137040844, dof=2, expected_freq=array([[24.08421053, 19.91578947],
       [19.70526316, 16.29473684],
       [ 8.21052632,  6.78947368]]))