## Question 1
The following table indicates the number of 6-point scores in an American rugby match in the 1979 season.

![](table1.png)

Based on these results, we create a Poisson distribution with the sample mean parameter  = 2.435. Is there any reason to believe that at a .05 level the number of scores is a Poisson variable?

In [1]:
# your answer here
import numpy as np
from scipy.stats import poisson
import scipy.stats as st
# Creating poisson distribution
mu=2.435
poisson_dist=poisson(mu)
# Creating expected values list
poisson_pmfs = np.array([poisson_dist.pmf(i) for i in range(0,7)])
with_tail = np.append(poisson_pmfs,1-poisson_pmfs.sum())
expected = with_tail*448
# check actual against expected list
st.chisquare([35,99,104,110,62,25,10,3],f_exp=expected)
expected
#we do not reject our hypothesis: this does seem to come from a poisson with 2.435!

array([ 39.24379068,  95.5586303 , 116.34263239,  94.43143662,
        57.48513704,  27.99526174,  11.36141039,   5.58170083])

## BONUS/OPTIONAL - Question 2
Let's analyze a discrete distribution. To analyze the number of defective items in a factory in the city of Medellín, we took a random sample of n = 60 articles and observed the number of defectives in the following table:

![](table2.png)

A poissón distribution was proposed since it is defined for x = 0,1,2,3, .... using the following model:

![](image1.png)

For some extra insights check the following link: https://online.stat.psu.edu/stat504/node/63/ 

Does the distribution of defective items follow this distribution?

In [2]:
# your code here
from scipy.stats import poisson

# check link

mu=28/60 # ?
poisson_dist=poisson(mu)
poisson_dist.pmf(0)

# to be continued ...

0.6270890852730561

## Question 3
A quality control engineer takes a sample of 10 tires that come out of an assembly line, and would like to verify on the basis of the data that follows, if the number of tires with defects observed over 200 days, if it is true that 5% of all tires have defects (that is, if the sample comes from a binomial population with n = 10 and p = 0.05). 

![](table3.png)


In [3]:
# your answer here
from scipy.stats import binom
# Create binomial distribution
n = 10
p = 0.05
binomial_dist = binom(n,p)

# Creating expected values list
binomial_pmfs = np.array([binomial_dist.pmf(i) for i in range(0,2)])
with_tail = np.append(binomial_pmfs,1-binomial_pmfs.sum())
expected = with_tail*(138+53+9)
print(expected)

# check actual against expected list
st.chisquare([138,53,9],f_exp=expected)

# Conclusion:
# we do reject our hypothesis: this does not seem to come from a binomial with n=10, p=0.05!

[119.74738785  63.02494097  17.22767118]


Power_divergenceResult(statistic=8.30617951954273, pvalue=0.015715783395951474)

## Question 4
A researcher gathers information about the patterns of Physical Activity of children in the fifth grade of primary school of a public school. He defines three categories of physical activity (Low, Medium, High). He also inquires about the regular consumption of sugary drinks at school, and defines two categories (Yes = consumed, No = not consumed). We would like to evaluate if there is an association between patterns of physical activity and the consumption of sugary drinks for the children of this school, at a level of 5% significance. The results are in the following table: 

![](table4.png)

In [4]:
#your answer here

activity_sugarydrinks =[[32,12],[14,22],[6,9]]
st.chi2_contingency(np.array(activity_sugarydrinks))

#return: statistic, p-value, degrees of freedom, expected probs if H0 holds
# underlying H0: drinking sugary drinks is independent of physical activity
# p-value at 0.004, so with 5% significance we can reject H0 and conclude that there is 'correlation'
# between physical activity and drinking sugary drinks

(10.712198008709638,
 0.004719280137040844,
 2,
 array([[24.08421053, 19.91578947],
        [19.70526316, 16.29473684],
        [ 8.21052632,  6.78947368]]))