## Question 1
The following table indicates the number of 6-point scores in an American rugby match in the 1979 season.

![](table1.png)

Based on these results, we create a Poisson distribution with the sample mean parameter  = 2.435. Is there any reason to believe that at a .05 level the number of scores is a Poisson variable?

In [34]:
# your answer here
# I think I have to build a poisson distribution with the sample mean parameter = 2.435 and run a chi-squared test to find
# out if the expected values are similar to the observed values (the frequency in each class).
import numpy as np
from scipy.stats import poisson
mu = 2.435

# pmf(k, mu, loc=0)
# in poisson pmf, k represents the intervals, so I guess we have 8 intervals?
# it's independent variable of my function

# I don't know how to use loc. I understand how it works on gaussian dist.but in this instance I have no idea.
# let's go down the rabbit hole
# https://stackoverflow.com/questions/48409212/what-is-the-meaning-of-mu-loc-and-size-in-the-scipy-stats-poisson
# «loc is the N-dimensional reference point of the distribution, that centroid being chosen appropriately to the function. 
# For this application, it's simply the left end of the desired distribution (scalar). This defaults to 0, and is only 
# changed if your application starts at something other than 0.»
# OK, so since our first class is zero I think we'll do fine leaving it to default

#poisson_dist = poisson.pmf(k, mu)
poisson_pmfs = np.array([poisson.pmf(k, mu)*448 for k in range(0,8)])
print(poisson_pmfs) # I multiply by the total to be able to compare the two lists (I could have converted the ibserved one instead)


[ 39.24379068  95.5586303  116.34263239  94.43143662  57.48513704
  27.99526174  11.36141039   3.95214776]


In [35]:
# The output looks good... let's compare it with the observed values
observed = np.array([35,99,104,110,62,25,10,3])
observed

array([ 35,  99, 104, 110,  62,  25,  10,   3])

In [36]:
import scipy.stats as st

# What is the number of ddof?
# https://www.lboro.ac.uk/media/media/schoolanddepartments/mlsc/downloads/1_4_gofit.pdf
# The number of degrees of freedom is k - p - 1
# Here we have 8 classes and we have p = 1 because we had to estimate one parameter (the mean)

st.chisquare(observed, poisson_pmfs, ddof = 1)

Power_divergenceResult(statistic=5.526588649191276, pvalue=0.4782489482044354)

In [ ]:
# since the null hypothesis is 'that the categorical data has the given frequencies.' and that our pvalue is
# higher than 0.05  we are confident that the number of scores follows a Poisson variable.

## BONUS/OPTIONAL - Question 2
Let's analyze a discrete distribution. To analyze the number of defective items in a factory in the city of Medellín, we took a random sample of n = 60 articles and observed the number of defectives in the following table:

![](table2.png)

A poissón distribution was proposed since it is defined for x = 0,1,2,3, .... using the following model:

![](image1.png)

For some extra insights check the following link: https://online.stat.psu.edu/stat504/node/63/ 

Does the distribution of defective items follow this distribution?

In [ ]:
# your code here

## Question 3
A quality control engineer takes a sample of 10 tires that come out of an assembly line, and would like to verify on the basis of the data that follows, if the number of tires with defects observed over 200 days, if it is true that 5% of all tires have defects (that is, if the sample comes from a binomial population with n = 10 and p = 0.05). 

![](table3.png)


In [37]:
# your answer here
n = 10
p = 0.05

# let's build the distribuiton 
# binom takes n and p as shape parameters.
binom_pmfs = st.binom.pmf([0,1], n, p)
binom_pmfs = np.append(binom_pmfs,1 - sum(binom_pmfs)) # the third bucket 2 or more
binom_pmfs = binom_pmfs*200 # to 'de-standardize' the table
print(binom_pmfs)
# the observations of the table above
observed = np.array([138,53,9])
print(observed)
# the actual test 
st.chisquare(observed, binom_pmfs) # there are no parameters to estimate, no adjustment needed to dof

[119.74738785  63.02494097  17.22767118]
[138  53   9]


Power_divergenceResult(statistic=8.30617951954273, pvalue=0.015715783395951474)

In [ ]:
# The sample follows a binomial distribution, the pvalue is lower thant 5% and we cannot reject the null hypothesis.

## Question 4
A researcher gathers information about the patterns of Physical Activity of children in the fifth grade of primary school of a public school. He defines three categories of physical activity (Low, Medium, High). He also inquires about the regular consumption of sugary drinks at school, and defines two categories (Yes = consumed, No = not consumed). We would like to evaluate if there is an association between patterns of physical activity and the consumption of sugary drinks for the children of this school, at a level of 5% significance. The results are in the following table: 

![](table4.png)

In [39]:
#your answer here
# Is this a contigency table? It looks like one.
# From what I read this is a contingency table.
# lets use chi2_contingency
# This function computes the chi-square statistic and p-value for the hypothesis test of independence of the observed 
# frequencies in the contingency table observed.
st.chi2_contingency([[32,12],[14,22],[6,9]])


(10.712198008709638,
 0.004719280137040844,
 2,
 array([[24.08421053, 19.91578947],
        [19.70526316, 16.29473684],
        [ 8.21052632,  6.78947368]]))

In [ ]:
# There is an association here is an association between patterns of physical activity and the consumption of sugary drinks 
# for the children of this school. The pvalue is lower than 5%.