## Question 1
The following table indicates the number of 6-point scores in an American rugby match in the 1979 season.

![](table1.png)

Based on these results, we create a Poisson distribution with the sample mean parameter  = 2.435. Is there any reason to believe that at a .05 level the number of scores is a Poisson variable?

In [4]:
import numpy as np
import scipy.stats as st
from scipy.stats import poisson

In [5]:
# your answer here
mu=2.435
poisson_dist=poisson(mu)
exp=[poisson_dist.pmf(i) for i in range(7)]
exp.append(poisson_dist.sf(6))
exp=np.array(exp)*448
exp

array([ 39.24379068,  95.5586303 , 116.34263239,  94.43143662,
        57.48513704,  27.99526174,  11.36141039,   5.58170083])

## BONUS/OPTIONAL - Question 2
Let's analyze a discrete distribution. To analyze the number of defective items in a factory in the city of Medellín, we took a random sample of n = 60 articles and observed the number of defectives in the following table:

![](table2.png)

A poissón distribution was proposed since it is defined for x = 0,1,2,3, .... using the following model:

![](image1.png)

For some extra insights check the following link: https://online.stat.psu.edu/stat504/node/63/ 

Does the distribution of defective items follow this distribution?

In [ ]:
# your code here

## Question 3
A quality control engineer takes a sample of 10 tires that come out of an assembly line, and would like to verify on the basis of the data that follows, if the number of tires with defects observed over 200 days, if it is true that 5% of all tires have defects (that is, if the sample comes from a binomial population with n = 10 and p = 0.05). 

![](table3.png)


In [15]:
from scipy.stats import binom
n=10
p=0.05 
binom_dist=binom(n,p)
exp=[binom_dist.pmf(i) for i in range(2)]
exp.append(binom_dist.sf(1))
exp=np.array(exp)*200
exp

array([119.74738785,  63.02494097,  17.22767118])

In [17]:
# your answer here
# H0: number tires with defects follows Binomial(10, 0.05)
# H1: number tires with defects doesn't follow Binomial(10, 0.05)
alpha=0.05 
obs=np.array([138, 53, 9])
exp=exp
stat, pval = st.chisquare(obs, f_exp=exp)
print(stat, pval)


8.30617951954277 0.015715783395951168


## Question 4
A researcher gathers information about the patterns of Physical Activity of children in the fifth grade of primary school of a public school. He defines three categories of physical activity (Low, Medium, High). He also inquires about the regular consumption of sugary drinks at school, and defines two categories (Yes = consumed, No = not consumed). We would like to evaluate if there is an association between patterns of physical activity and the consumption of sugary drinks for the children of this school, at a level of 5% significance. The results are in the following table: 

![](table4.png)

In [10]:
#your answer here
#H0: the patterns of physical activity and the consumption of sugary drinks in children are not dependent
#H1: they are dependent

alpha=0.05
samp =np.array([[32, 12], [14, 22], [6, 9]])
_,pval,_,_=st.chi2_contingency(samp)
_,pval,_,_

(array([[24.08421053, 19.91578947],
        [19.70526316, 16.29473684],
        [ 8.21052632,  6.78947368]]),
 0.004719280137040844,
 array([[24.08421053, 19.91578947],
        [19.70526316, 16.29473684],
        [ 8.21052632,  6.78947368]]),
 array([[24.08421053, 19.91578947],
        [19.70526316, 16.29473684],
        [ 8.21052632,  6.78947368]]))

In [11]:
pval<alpha

True

In [ ]:
#reject H0