## Question 1
The following table indicates the number of 6-point scores in an American rugby match in the 1979 season.

![](table1.png)

Based on these results, we create a Poisson distribution with the sample mean parameter  = 2.435. Is there any reason to believe that at a .05 level the number of scores is a Poisson variable?

In [15]:
import numpy as np
import scipy.stats as st

In [2]:
# your answer here

# H0: dist ~ poisson(0.2435)
# H1: dist !~ poisson(0.2435)

alpha = 0.05

O = np.array([35, 99, 104, 110, 62, 25, 10, 3])

from scipy.stats import poisson

p = 2.435

poisson_dist = poisson(p)
poisson_pmf = np.array([poisson_dist.pmf(i) for i in range(1,8)])

with_tail = np.append(poisson_pmf, poisson_dist.sf(7))

E = with_tail 
E

array([0.21330051, 0.25969338, 0.21078446, 0.12831504, 0.06248942,
       0.02536029, 0.00882176, 0.0036374 ])

## BONUS/OPTIONAL - Question 2
Let's analyze a discrete distribution. To analyze the number of defective items in a factory in the city of Medellín, we took a random sample of n = 60 articles and observed the number of defectives in the following table:

![](table2.png)

A poissón distribution was proposed since it is defined for x = 0,1,2,3, .... using the following model:

![](image1.png)

For some extra insights check the following link: https://online.stat.psu.edu/stat504/node/63/ 

Does the distribution of defective items follow this distribution?

In [3]:
# your code here

## Question 3
A quality control engineer takes a sample of 10 tires that come out of an assembly line, and would like to verify on the basis of the data that follows, if the number of tires with defects observed over 200 days, if it is true that 5% of all tires have defects (that is, if the sample comes from a binomial population with n = 10 and p = 0.05). 

![](table3.png)


In [36]:
# your answer here

# H0: dist ~ binomial(0.05)
# H1: dist !~ binomial(0.05)

O = [138,53,9]

p = 0.05
n = 10

from scipy.stats import binom

binom_dist = binom(n,p)

binom_pmf = np.array([binom_dist.pmf(i) for i in range(0,2)])

with_tail = np.append(binom_pmf, binom_dist.sf(1))

E = with_tail * 200
E

array([119.74738785,  63.02494097,  17.22767118])

In [37]:

print(with_tail)

[0.59873694 0.3151247  0.08613836]


In [38]:
stats, p_value = st.chisquare(f_obs=O, f_exp=E)

print(stats)
print(p_value)

p_value < 0.05

8.30617951954277
0.015715783395951168


True

In [ ]:
# we reject H0

## Question 4
A researcher gathers information about the patterns of Physical Activity of children in the fifth grade of primary school of a public school. He defines three categories of physical activity (Low, Medium, High). He also inquires about the regular consumption of sugary drinks at school, and defines two categories (Yes = consumed, No = not consumed). We would like to evaluate if there is an association between patterns of physical activity and the consumption of sugary drinks for the children of this school, at a level of 5% significance. The results are in the following table: 

![](table4.png)

In [21]:
#your answer here

alpha = 0.05

# H0:  physical activity is independent of consumptions of sugary drinks
# H1:  physical activity is dependent on consumptions of sugary drinks

data = np.array([[32,12],[14,22],[6,9]])

st.chi2_contingency(data)

(10.712198008709638,
 0.004719280137040844,
 2,
 array([[24.08421053, 19.91578947],
        [19.70526316, 16.29473684],
        [ 8.21052632,  6.78947368]]))

In [23]:
0.004719280137040844 < alpha

True

In [ ]:
# we reject H0

# we assume that physical activity is dependent on consumptions of sugary drinks