## Question 1
The following table indicates the number of 6-point scores in an American rugby match in the 1979 season.

![](table1.png)

Based on these results, we create a Poisson distribution with the sample mean parameter  = 2.435. Is there any reason to believe that at a .05 level the number of scores is a Poisson variable?

In [1]:
# your answer here
#sig = 0.05
#mu = 2.435
#H0: poisson
#H1: not poisson

import scipy.stats as st
from scipy.stats import poisson
import numpy as np

poisson_pmfs = np.array([poisson(2.435).pmf(i) for i in range(1,8)])
poisson_pmfs = np.array([poisson(2.435).pmf(i) for i in range(1,8)])
poisson_pmfs

array([0.21330051, 0.25969338, 0.21078446, 0.12831504, 0.06248942,
       0.02536029, 0.00882176])

In [2]:
expected = np.append(poisson_pmfs, 1-poisson_pmfs.sum())*448
expected

array([ 95.5586303 , 116.34263239,  94.43143662,  57.48513704,
        27.99526174,  11.36141039,   3.95214776,  40.87334376])

In [3]:
st.chisquare([35,99,104,110,62,25,10,3],f_exp=expected)

Power_divergenceResult(statistic=191.93184027673232, pvalue=5.85583627060059e-38)

In [ ]:
# pvalue is low so the null hypothesis is rejected and therefore it's not a poisson.

## BONUS/OPTIONAL - Question 2
Let's analyze a discrete distribution. To analyze the number of defective items in a factory in the city of Medellín, we took a random sample of n = 60 articles and observed the number of defectives in the following table:

![](table2.png)

A poissón distribution was proposed since it is defined for x = 0,1,2,3, .... using the following model:

![](image1.png)

For some extra insights check the following link: https://online.stat.psu.edu/stat504/node/63/ 

Does the distribution of defective items follow this distribution?

In [ ]:
# your code here

## Question 3
A quality control engineer takes a sample of 10 tires that come out of an assembly line, and would like to verify on the basis of the data that follows, if the number of tires with defects observed over 200 days, if it is true that 5% of all tires have defects (that is, if the sample comes from a binomial population with n = 10 and p = 0.05). 

![](table3.png)


In [5]:
# your answer here
import pandas as pd
import numpy as np
(138*0+53*1+2*9)/(200*10)


0.0355

In [7]:
from scipy.stats import binom
#H0: mu = binomial_dist
#H1: mu != binomial_dist
#sig = 5%

binomial_dist = binom(10,0,0.05)
binom_pmfs = np.array([binomial_dist.pmf(i) for i in range(0,2)])
expected = np.append(binom_pmfs,1-binom_pmfs.sum())*200
st.chisquare([138,53,9],f_exp=expected)

# the pvalue is low so it's not a binomial distribution

Power_divergenceResult(statistic=inf, pvalue=0.0)

## Question 4
A researcher gathers information about the patterns of Physical Activity of children in the fifth grade of primary school of a public school. He defines three categories of physical activity (Low, Medium, High). He also inquires about the regular consumption of sugary drinks at school, and defines two categories (Yes = consumed, No = not consumed). We would like to evaluate if there is an association between patterns of physical activity and the consumption of sugary drinks for the children of this school, at a level of 5% significance. The results are in the following table: 

![](table4.png)

In [ ]:
#your answer here

#significance 0.05
#H0: no association between physical activity and consumption of sugary drinks in this school.
#H1: association between patterns of physical activity and the consumption of sugary drinks in this school.

In [10]:
import scipy.stats as st
table = [[32,12],[14,22],[6,9]]

st.chi2_contingency(np.array(table))

#the pvalue is low, so we can conclude that there is an association between patterns of physical activity and the consumption of sugary drinks in this school.

(10.712198008709638,
 0.004719280137040844,
 2,
 array([[24.08421053, 19.91578947],
        [19.70526316, 16.29473684],
        [ 8.21052632,  6.78947368]]))